### ISSUE TITLE
OutBounce

### ISSUE THREAD

**Issue by SiENcE** [rxi/flux#1]
I need an OutBounce ease, is it possible to add?

**Comment by Silver-Hawk** [comment]
I did a bounce in/out hack for the flux library earlier, the thing is the bounce is conditional so it's a little trickier for a one liner like the other functions, but i can give you a gist for it when i get home :)

Hopefully i can clean it up and make a pull request later on

**Comment by SiENcE** [comment]
Yes I know :), I also tried adding one, but i can only make a bad hack.

I would appreciate it. Thx very much!

**Comment by Silver-Hawk** [comment]
Here SiENcE this should easily do the trick, just use it as you normally would with :ease("BounceIn"/"BounceOut")

**Comment by Silver-Hawk** [comment]
https://gist.github.com/Silver-Hawk/95c00a09c1ca7dca6980 ups here :P

**Comment by SiENcE** [comment]
Hey Silver-Hawk thanks for sharing!

Your solution is nice as it uses the the flux way of creating this functions. But bounce is global which is no solution for me. I took yours and created an solution without the need to have bounce globally defined. But for now it's only "bounceout".

https://gist.github.com/SiENcE/cbf9bd3a33fc647671a3

**Comment by aggsol** [comment]
@kikito has both bounce function in his tweening lib, maybe you could use those.

https://github.com/kikito/tween.lua
